services:
  app:
    build: .
    container_name: pet-app-api
    command: python Server.py
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
  db:
    image: postgres
    ports:
    - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}